// Generated by CoffeeScript 1.3.3
(function() {
  var Timers;

  Timers = (function() {

    function Timers(opts) {
      this.projectId = opts.projectId;
      this.storyId = opts.storyId;
      this.pivotalToken = opts.pivotalToken;
      if (this.storyId != null) {
        this.setupSingle();
      } else {
        this.setup();
      }
    }

    Timers.prototype.setupSingle = function() {
      return console.log('setting up single');
    };

    Timers.prototype.setup = function() {
      return console.log('setting up all');
    };

    return Timers;

  })();

  window.ERR = function(msg) {
    alert(msg);
    throw new Error(msg);
  };

  $(function() {
    chrome.extension.sendMessage({
      method: 'login'
    }, function(response) {
      var projectId, storyId, uri;
      if (response.error != null) {
        ERR('Pivotal Meet Harvest Error: There was a problem logging in to the Pivotal Tracker API or the Harvest API. See extension options.');
      }
      uri = document.location.href.split('/');
      if (typeof uri[4] === 'undefined' || uri[3] !== 'projects') {
        return;
      }
      projectId = parseInt(uri[4]);
      storyId = null;
      if (typeof uri[5] !== 'undefined' && uri[5] === 'stories') {
        return storyId = parseInt(uri[6]);
      }
    });
    return chrome.extension.sendMessage({
      method: 'getProjects'
    }, function(response) {
      return console.log(response);
    });
  });

}).call(this);
