// Generated by CoffeeScript 1.3.3
(function() {
  var Timers;

  Timers = (function() {

    function Timers(opts) {
      console.log(opts);
      this.pivotalProject = opts.pivotalProject;
      this.harvestProject = opts.harvestProject;
      this.storyId = opts.storyId;
      if (this.storyId != null) {
        this.setupSingle();
      } else {
        this.setup();
      }
    }

    Timers.prototype.setupSingle = function() {
      return console.log('setting up single');
    };

    Timers.prototype.setup = function() {
      return console.log('setting up all');
    };

    return Timers;

  })();

  window.ERR = function(msg) {
    msg = 'Pivotal Meet Harvest Error: ' + msg;
    throw new Error(msg);
  };

  $(function() {
    return chrome.extension.sendMessage({
      method: 'login'
    }, function(response) {
      var projectId, storyId, uri;
      if (response.error != null) {
        ERR('There was a problem logging in to the Pivotal Tracker API or the Harvest API. See extension options.');
      }
      uri = document.location.href.split('/');
      if (typeof uri[4] === 'undefined' || uri[3] !== 'projects') {
        return;
      }
      projectId = parseInt(uri[4]);
      storyId = null;
      if (typeof uri[5] !== 'undefined' && uri[5] === 'stories') {
        storyId = parseInt(uri[6]);
      }
      return chrome.extension.sendMessage({
        method: 'getProjectPair',
        pivotalId: projectId
      }, function(response) {
        var t;
        if (response.error != null) {
          ERR('This project is not mapped to any project in Harvest. See extension options.');
          return;
        }
        return t = new Timers({
          harvestProject: response.harvestProject,
          storyId: storyId,
          pivotalProject: response.pivotalProject
        });
      });
    });
  });

}).call(this);
