// Generated by CoffeeScript 1.3.3
var PivotalAPI;

PivotalAPI = (function() {

  function PivotalAPI(user, pass) {
    var self;
    this.url = 'https://www.pivotaltracker.com/services/v3/';
    self = this;
    $.ajax({
      url: this.url + 'tokens/active',
      type: 'POST',
      async: false,
      data: {
        username: user,
        password: pass
      },
      success: function(data) {
        var $guid;
        $guid = $(data).find('guid');
        return self.token = $guid.text();
      },
      error: function(xhr, status, error) {
        throw Error('There was a problem logging in to the Pivotal Tracker API. See options page.');
      }
    });
  }

  PivotalAPI.prototype.getAllProjects = function() {
    var data, id, name, project, projects, _i, _len, _ref;
    data = this.GET('projects', null);
    projects = [];
    _ref = $(data).find('project');
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      project = _ref[_i];
      name = $(project).find('name').first().text();
      id = $(project).find('id').first().text();
      projects.push({
        name: name,
        id: id
      });
    }
    return projects;
  };

  PivotalAPI.prototype.getStories = function(pivotalProjectId) {
    var data, s, stories, story, _i, _len, _ref;
    data = this.GET('projects/' + pivotalProjectId + '/stories');
    stories = [];
    _ref = $(data).find('story');
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      story = _ref[_i];
      s = {
        id: $(story).find('id').text(),
        name: $(story).find('name').text()
      };
      stories.push(s);
    }
    return stories;
  };

  PivotalAPI.prototype.POST = function(path, data) {
    return this.HTTP('POST', path, data)(function() {});
  };

  PivotalAPI.prototype.GET = function(path, data) {
    return this.HTTP('GET', path, data);
  };

  PivotalAPI.prototype.HTTP = function(method, path, data) {
    var returnData;
    returnData = false;
    $.ajax({
      url: this.url + path,
      type: method,
      async: false,
      data: data,
      headers: {
        'X-TrackerToken': this.token
      },
      success: function(data) {
        return returnData = data;
      },
      error: function() {
        return returnData = false;
      }
    });
    return returnData;
  };

  return PivotalAPI;

})();
